import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Movie list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <nav className=""></nav>
      </main>
    </>
  );
};

export default Home;

import React from 'react'

export const Header = () => {
  return (
    <header className="flex flex-row justify-between bg-red-500 p-4">
    <Logo />
    <AuthShowcase />
  </header>
  )
}


const Logo: React.FC = () => {
  return (
    <Link href="/">
      <Image alt="logo" width={50} height={50} src="/assets/t3-logo.png" />
    </Link>
  );
};

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data } = api.user.icon.useQuery();

  const avatarUri = data?.avatar;

  return (
    <div className="flex items-center justify-center text-white">
      <button
        className="flex items-center justify-between gap-4 rounded-2xl bg-white/10 p-3 pr-4 text-center font-semibold no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData && avatarUri && (
          <Image
            alt="user-icon"
            src={avatarUri}
            width={35}
            height={35}
            className="rounded-full border"
          />
        )}
        {sessionData ? sessionData.user.name ?? "SignOut" : "Sign in"}
      </button>
    </div>
  );
};
